const PREFIX = 'AUTH';

const ActionType = {
  SET_AUTH_DATA: `${PREFIX}/SET_AUTH_DATA`,
  SET_AUTHORIZED: `${PREFIX}/SET_AUTHORIZED`,
  SET_AUTH_LOADING: `${PREFIX}/SET_AUTH_LOADING`,
  UPDATE_NAME: `${PREFIX}/UPDATE_NAME`,
  SET_DATA_UPDATING: `${PREFIX}/SET_DATA_UPDATING`,
  UPDATE_PHOTO: `${PREFIX}/UPDATE_PHOTO`,
  SET_PHOTO_UPDATING: `${PREFIX}/SET_PHOTO_UPDATING`,
  SET_ERROR: `${PREFIX}/SET_ERROR`,
  RESET_AUTH_DATA: `${PREFIX}/RESET_AUTH_DATA`,
};

export default ActionType;
