const PREFIX = 'REMINDERS';

const ActionType = {
  ADD_REMINDER: `${PREFIX}/ADD_REMINDER`,
  UPDATE_REMINDER: `${PREFIX}/UPDATE_REMINDER`,
  UPDATE_CREATED_REMINDER: `${PREFIX}/UPDATE_CREATED_REMINDER`,
  REMOVE_REMINDER: `${PREFIX}/REMOVE_REMINDER`,
  SET_EDITABLE_ID: `${PREFIX}/SET_EDITABLE_ID`,
  SET_REMINDERS: `${PREFIX}/SET_REMINDERS`,
  SET_LOADING: `${PREFIX}/SET_LOADING`,
  SET_ERROR: `${PREFIX}/SET_ERROR`,
  RESET: `${PREFIX}/RESET`,
};

export default ActionType;
